/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'propertyType' : Type,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
  'budget' : bigint,
  'location' : string,
}
export interface Property {
  'id' : bigint,
  'status' : Status,
  'title' : string,
  'propertyType' : Type,
  'bedrooms' : [] | [bigint],
  'area' : bigint,
  'isAvailable' : boolean,
  'description' : string,
  'bathrooms' : [] | [bigint],
  'price' : bigint,
  'location' : string,
}
export type Status = { 'rented' : null } |
  { 'sold' : null } |
  { 'available' : null };
export type Time = bigint;
export type Type = { 'retail' : null } |
  { 'villa' : null } |
  { 'apartment' : null } |
  { 'office' : null };
export interface _SERVICE {
  'addProperty' : ActorMethod<[Property], bigint>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getAvailableProperties' : ActorMethod<[], Array<Property>>,
  'getProperty' : ActorMethod<[bigint], [] | [Property]>,
  'submitInquiry' : ActorMethod<
    [string, string, string, Type, string, bigint, string],
    bigint
  >,
  'updatePropertyStatus' : ActorMethod<[bigint, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];