/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({
  'rented' : IDL.Null,
  'sold' : IDL.Null,
  'available' : IDL.Null,
});
export const Type = IDL.Variant({
  'retail' : IDL.Null,
  'villa' : IDL.Null,
  'apartment' : IDL.Null,
  'office' : IDL.Null,
});
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'title' : IDL.Text,
  'propertyType' : Type,
  'bedrooms' : IDL.Opt(IDL.Nat),
  'area' : IDL.Nat,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'bathrooms' : IDL.Opt(IDL.Nat),
  'price' : IDL.Nat,
  'location' : IDL.Text,
});
export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'propertyType' : Type,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'budget' : IDL.Nat,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProperty' : IDL.Func([Property], [IDL.Nat], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getAvailableProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Type, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updatePropertyStatus' : IDL.Func([IDL.Nat, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({
    'rented' : IDL.Null,
    'sold' : IDL.Null,
    'available' : IDL.Null,
  });
  const Type = IDL.Variant({
    'retail' : IDL.Null,
    'villa' : IDL.Null,
    'apartment' : IDL.Null,
    'office' : IDL.Null,
  });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'title' : IDL.Text,
    'propertyType' : Type,
    'bedrooms' : IDL.Opt(IDL.Nat),
    'area' : IDL.Nat,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'bathrooms' : IDL.Opt(IDL.Nat),
    'price' : IDL.Nat,
    'location' : IDL.Text,
  });
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'propertyType' : Type,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'budget' : IDL.Nat,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addProperty' : IDL.Func([Property], [IDL.Nat], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getAvailableProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Type, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updatePropertyStatus' : IDL.Func([IDL.Nat, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };