/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Property {
    id: bigint;
    status: Status;
    title: string;
    propertyType: Type;
    bedrooms?: bigint;
    area: bigint;
    isAvailable: boolean;
    description: string;
    bathrooms?: bigint;
    price: bigint;
    location: string;
}
export type Time = bigint;
export interface Inquiry {
    propertyType: Type;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
    budget: bigint;
    location: string;
}
export enum Status {
    rented = "rented",
    sold = "sold",
    available = "available"
}
export enum Type {
    retail = "retail",
    villa = "villa",
    apartment = "apartment",
    office = "office"
}
export interface backendInterface {
    addProperty(property: Property): Promise<bigint>;
    getAllInquiries(): Promise<Array<Inquiry>>;
    getAllProperties(): Promise<Array<Property>>;
    getAvailableProperties(): Promise<Array<Property>>;
    getProperty(propertyId: bigint): Promise<Property | null>;
    submitInquiry(name: string, phone: string, email: string, propertyType: Type, location: string, budget: bigint, message: string): Promise<bigint>;
    updatePropertyStatus(propertyId: bigint, newStatus: Status): Promise<void>;
}
import type { Inquiry as _Inquiry, Property as _Property, Status as _Status, Time as _Time, Type as _Type } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProperty(arg0: Property): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProperty(to_candid_Property_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProperty(to_candid_Property_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProperties();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProperties();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableProperties();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableProperties();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperty(arg0: bigint): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: string, arg3: Type, arg4: string, arg5: bigint, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, to_candid_Type_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, to_candid_Type_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async updatePropertyStatus(arg0: bigint, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePropertyStatus(arg0, to_candid_Status_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePropertyStatus(arg0, to_candid_Status_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Inquiry_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Property_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Property): Property {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Property]): Property | null {
    return value.length === 0 ? null : from_candid_Property_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    title: string;
    propertyType: _Type;
    bedrooms: [] | [bigint];
    area: bigint;
    isAvailable: boolean;
    description: string;
    bathrooms: [] | [bigint];
    price: bigint;
    location: string;
}): {
    id: bigint;
    status: Status;
    title: string;
    propertyType: Type;
    bedrooms?: bigint;
    area: bigint;
    isAvailable: boolean;
    description: string;
    bathrooms?: bigint;
    price: bigint;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n15(_uploadFile, _downloadFile, value.status),
        title: value.title,
        propertyType: from_candid_Type_n10(_uploadFile, _downloadFile, value.propertyType),
        bedrooms: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.bedrooms)),
        area: value.area,
        isAvailable: value.isAvailable,
        description: value.description,
        bathrooms: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.bathrooms)),
        price: value.price,
        location: value.location
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    propertyType: _Type;
    name: string;
    email: string;
    message: string;
    timestamp: _Time;
    phone: string;
    budget: bigint;
    location: string;
}): {
    propertyType: Type;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
    budget: bigint;
    location: string;
} {
    return {
        propertyType: from_candid_Type_n10(_uploadFile, _downloadFile, value.propertyType),
        name: value.name,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phone: value.phone,
        budget: value.budget,
        location: value.location
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    retail: null;
} | {
    villa: null;
} | {
    apartment: null;
} | {
    office: null;
}): Type {
    return "retail" in value ? Type.retail : "villa" in value ? Type.villa : "apartment" in value ? Type.apartment : "office" in value ? Type.office : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rented: null;
} | {
    sold: null;
} | {
    available: null;
}): Status {
    return "rented" in value ? Status.rented : "sold" in value ? Status.sold : "available" in value ? Status.available : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Property>): Array<Property> {
    return value.map((x)=>from_candid_Property_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Property_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Property): _Property {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Type_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): _Type {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Status;
    title: string;
    propertyType: Type;
    bedrooms?: bigint;
    area: bigint;
    isAvailable: boolean;
    description: string;
    bathrooms?: bigint;
    price: bigint;
    location: string;
}): {
    id: bigint;
    status: _Status;
    title: string;
    propertyType: _Type;
    bedrooms: [] | [bigint];
    area: bigint;
    isAvailable: boolean;
    description: string;
    bathrooms: [] | [bigint];
    price: bigint;
    location: string;
} {
    return {
        id: value.id,
        status: to_candid_Status_n3(_uploadFile, _downloadFile, value.status),
        title: value.title,
        propertyType: to_candid_Type_n5(_uploadFile, _downloadFile, value.propertyType),
        bedrooms: value.bedrooms ? candid_some(value.bedrooms) : candid_none(),
        area: value.area,
        isAvailable: value.isAvailable,
        description: value.description,
        bathrooms: value.bathrooms ? candid_some(value.bathrooms) : candid_none(),
        price: value.price,
        location: value.location
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    rented: null;
} | {
    sold: null;
} | {
    available: null;
} {
    return value == Status.rented ? {
        rented: null
    } : value == Status.sold ? {
        sold: null
    } : value == Status.available ? {
        available: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): {
    retail: null;
} | {
    villa: null;
} | {
    apartment: null;
} | {
    office: null;
} {
    return value == Type.retail ? {
        retail: null
    } : value == Type.villa ? {
        villa: null
    } : value == Type.apartment ? {
        apartment: null
    } : value == Type.office ? {
        office: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
